### ISSUE TITLE
next next-20150331 build errors (31 mar 2015)

### ISSUE THREAD

**Issue by hellbentv** [kernelci/kernel-bugs#10]
I've haven't dug deeper into these build errors and want to make sure you are aware.

 http://storage.kernelci.org/next/next-20150331/arm-ep93xx_defconfig/build.log
 http://storage.kernelci.org/next/next-20150331/arm-ebsa110_defconfig/build.log
 http://storage.kernelci.org/next/next-20150331/arm-rpc_defconfig/build.log

 The full build report is here:

 http://kernelci.org/build/next/kernel/next-20150331/

**Comment by EmbeddedAndroid** [comment]
Fix has hit -next

http://kernelci.org/build/next/kernel/next-20150407/
