### ISSUE TITLE
arm-soc v4.0-rc4-354-ga0690e6586df boot failures (2 apr 2015)

### ISSUE THREAD

**Issue by hellbentv** [kernelci/kernel-bugs#11]
this commit seems to break the boot on IFC6410, it was initially
reported on kernelci.org, see report and bootlog [1].

running git bisect led me to:

e5fdad68d47ed344832b7ca4e18b2e9708d8141e is the first bad commit
commit e5fdad68d47ed344832b7ca4e18b2e9708d8141e
Author: Andy Gross agross@codeaurora.org
Date:   Mon Feb 9 16:01:06 2015 -0600

```
soc: qcom: gsbi: Add support for ADM CRCI muxing

This patch adds automatic configuration for the ADM CRCI muxing required to
support DMA operations for GSBI clients.  The GSBI mode and
```

instance determine
    the correct TCSR ADM CRCI MUX value that must be programmed so that the DMA
    works properly.

```
Signed-off-by: Andy Gross <agross@codeaurora.org>
Signed-off-by: Kumar Gala <galak@codeaurora.org>
```

[1] http://kernelci.org/boot/all/job/arm-soc/kernel/v4.0-rc4-354-ga0690e6586df/

**Comment by khilman** [comment]
email thread where issue is reported/discussed:
http://lists.infradead.org/pipermail/linux-arm-kernel/2015-April/335209.html

**Comment by khilman** [comment]
I think this one should be closed now, yeah?

**Comment by khilman** [comment]
IFC6410 has been booting well for awhile now in arm-soc: http://kernelci.org/boot/?arm-soc&ifc6410

Closing.
