### ISSUE TITLE
ICE regression in next (29 mar 2015)

### ISSUE THREAD

**Issue by EmbeddedAndroid** [kernelci/kernel-bugs#12]
../mm/migrate.c: In function 'migrate_pages':
../mm/migrate.c:1148:1: internal compiler error: in push_minipool_fix, at config/arm/arm.c:13101
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.7/README.Bugs for instructions.
Preprocessed source stored into /tmp/ccO1Nz1m.out file, please attach
this to your bugreport.
make[2]: **\* [mm/migrate.o] Error 1
make[2]: Target `__build' not remade because of errors.
make[1]: **\* [mm] Error 2

Thread with pending fix:
https://lkml.org/lkml/2015/4/1/171

**Comment by khilman** [comment]
Andrew Morten picked up the fixes for this, and should be in linux-next starting with 20150406.
To be verified.

**Comment by EmbeddedAndroid** [comment]
next-20150408 LGTM. 

http://kernelci.org/boot/all/job/next/kernel/next-20150408/
