### ISSUE TITLE
imx6 platforms failing to boot with multi_v7_defconfig on next-20150428

### ISSUE THREAD

**Issue by EmbeddedAndroid** [kernelci/kernel-bugs#20]
This issue has been bisected by @khilman and myself. @khilman to report the issue.

git bisect start
bad: [63382678150626a85e694031769496d58245d430] Add linux-next specific files for 20150428
git bisect bad 63382678150626a85e694031769496d58245d430
good: [39a8804455fb23f09157341d3ba7db6d7ae6ee76] Linux 4.0
git bisect good 39a8804455fb23f09157341d3ba7db6d7ae6ee76
good: [6d50ff91d9780263160262daeb6adfdda8ddbc6c] Merge tag 'locks-v4.1-1' of git://git.samba.org/jlayton/linux
git bisect good 6d50ff91d9780263160262daeb6adfdda8ddbc6c
good: [1fc149933fd49a5b0e7738dc0853dbfbac4ae0e1] Merge tag 'char-misc-4.1-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/gregkh/char-misc
git bisect good 1fc149933fd49a5b0e7738dc0853dbfbac4ae0e1
good: [668b54a1c2c25bde34cd9c077b1c5f03b46bcb49] Merge tag 'blackfin-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/realmz6/blackfin-linux
git bisect good 668b54a1c2c25bde34cd9c077b1c5f03b46bcb49
bad: [b2811803634af07fa59a8b5393529fa45c47c94d] Merge remote-tracking branch 'parisc-hd/for-next'
git bisect bad b2811803634af07fa59a8b5393529fa45c47c94d
good: [c8b3fd0ce313443731e8fd6d5a541085eb465f99] Merge tag 'pm+acpi-4.1-rc1-2' of git://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm
git bisect good c8b3fd0ce313443731e8fd6d5a541085eb465f99
good: [3cc7839a4256cf58831f95bb39b3e3053d2eefb4] Merge remote-tracking branch 'cortex-m/for-next'
git bisect good 3cc7839a4256cf58831f95bb39b3e3053d2eefb4
good: [4ab66f83f8246aff05db3e64d2aded2687432785] Merge branch 'sunxi/defconfig-for-4.2' into sunxi/for-next
git bisect good 4ab66f83f8246aff05db3e64d2aded2687432785
bad: [0e5de2bd53e0f08a1aa4358c4f91c750d2a8a555] Merge remote-tracking branch 'renesas/next'
git bisect bad 0e5de2bd53e0f08a1aa4358c4f91c750d2a8a555
bad: [4b64434c6b387947b78ab29ee894e128f45f3ddc] Merge remote-tracking branch 'keystone/next'
git bisect bad 4b64434c6b387947b78ab29ee894e128f45f3ddc
bad: [0cccb966114ba5a35bba85bf472c18eff1757d93] MAINTAINERS: add new folders into IMX entry
git bisect bad 0cccb966114ba5a35bba85bf472c18eff1757d93
bad: [4631960d26da2172d1220c196e0fad927fa16535] ARM: imx6: set initial power mode in pm function
git bisect bad 4631960d26da2172d1220c196e0fad927fa16535
good: [fa1369fb16fbd6a61a19f7ca0eb7081830c9a625] ARM: imx: use dynamic mapping for CCM
git bisect good fa1369fb16fbd6a61a19f7ca0eb7081830c9a625
good: [c1924645cf46273f5f0ffb48d4a2e5ad5a43a86a] ARM: imx5: let pm code map CCM block on its own
git bisect good c1924645cf46273f5f0ffb48d4a2e5ad5a43a86a
first bad commit: [4631960d26da2172d1220c196e0fad927fa16535] ARM: imx6: set initial power mode in pm function

**Comment by khilman** [comment]
Reported:
http://lists.infradead.org/pipermail/linux-arm-kernel/2015-April/339616.html

**Comment by EmbeddedAndroid** [comment]
Proposed fix is here:
http://www.spinics.net/lists/arm-kernel/msg414675.html

Patch has been queued to build and boot test in my to-build branch.

**Comment by EmbeddedAndroid** [comment]
Fixes are now in next-20150504, closing...
