### ISSUE TITLE
next-20150609: multiple boot failures (imx, omap)

### ISSUE THREAD

**Issue by khilman** [kernelci/kernel-bugs#36]
http://kernelci.org/boot/all/job/next/kernel/next-20150609/

**Comment by khilman** [comment]
Tyler bisected on imx6 down to b6d2233f2916 of/platform: Use platform_device interface.

Bisecting on OMAP was not as conclusive, but reverting that same patch got things booting again for OMAP as well.

Reported: http://www.spinics.net/lists/devicetree/msg83368.html

**Comment by khilman** [comment]
Offending patches reverted (see thread above).  Should be fixed in next linux-next.

**Comment by EmbeddedAndroid** [comment]
The offending series has been reverted and the failures are not present in the latest next.

http://kernelci.org/boot/all/job/next/kernel/next-20150615/
