### ISSUE TITLE
next-20150619: omap5-evm, peach-pi and beagle-xm boot failures.

### ISSUE THREAD

**Issue by EmbeddedAndroid** [kernelci/kernel-bugs#39]
Boot failures:

http://kernelci.org/boot/all/job/next/kernel/next-20150619/

@khilman and I both bisected and confirmed revert the following commit gets the platforms booting again.

881bd58d6e9eba4240b9dbc49fdc03a3374d7508 is the first bad commit
commit 881bd58d6e9eba4240b9dbc49fdc03a3374d7508
Author: Sebastian Andrzej Siewior bigeasy@linutronix.de
Date:   Wed Jun 17 10:33:50 2015 +0200

```
futex: Lower the lock contention on the HB lock during wake up

wake_futex_pi() wakes the task before releasing the hash bucket lock
(HB). The first thing the woken up task usually does is to acquire the
lock which requires the HB lock. On SMP Systems this leads to blocking
on the HB lock which is released by the owner shortly after.
This patch rearranges the unlock path by first releasing the HB lock and
then waking up the task.

Originally-from: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Steven Rostedt <rostedt@goodmis.org>
Cc: Mike Galbraith <umgwanakikbuti@gmail.com>
Cc: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
Cc: Davidlohr Bueso <dave@stgolabs.net>
Link: http://lkml.kernel.org/r/20150617083350.GA2433@linutronix.de
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
```

@khilman to report issue on list.

**Comment by khilman** [comment]
Reported: https://lkml.org/lkml/2015/6/19/411

**Comment by EmbeddedAndroid** [comment]
@khilman manually tested the fix provided by tglx and I've applied it to my to-build branch based on next-20150619.

http://kernelci.org/boot/all/job/tbaker/kernel/v4.1-rc8-12377-g16828e696d85/

It resolves the issues reported here.

**Comment by EmbeddedAndroid** [comment]
This issue has been resolved.

http://kernelci.org/boot/all/job/next/kernel/next-20150710/
