### ISSUE TITLE
next-20150901: hikey: new boot failures

### ISSUE THREAD

**Issue by khilman** [kernelci/kernel-bugs#52]
http://kernelci.org/boot/hi6220-hikey/

It's actually been failing in linux-next for awhile now.

**Comment by khilman** [comment]
Bisected, reported: http://lists.infradead.org/pipermail/linux-arm-kernel/2015-September/367479.html

**Comment by EmbeddedAndroid** [comment]
Offending commits have been reverted, hikey is booting fine now.

http://kernelci.org/boot/all/job/next/kernel/next-20150922/
