### ISSUE TITLE
next-20150924: arndale: new boot failure

### ISSUE THREAD

**Issue by khilman** [kernelci/kernel-bugs#58]
http://kernelci.org/boot/exynos5250-arndale/job/next/kernel/next-20150925/defconfig/exynos_defconfig/lab/lab-khilman/?_id=5605088759b51466d06c3259

**Comment by khilman** [comment]
Bisected:
https://ci.linaro.org/view/people/job/tbaker-boot-bisect-bot/95/console

**Comment by EmbeddedAndroid** [comment]
Closing, as we have removed ip=dhcp from the kernel command line.
