### ISSUE TITLE
TK1: devfreq kernel spam on next-20160118

### ISSUE THREAD

**Issue by mattface** [kernelci/kernel-bugs#74]
[   10.465537] devfreq 6000c800.actmon: Couldn't update frequency transition information.

This is spammed to the kernel log and causes the board to become almost totally unresponsive. So far the LAVA boot jobs are not failing because eventually the job completes, but takes around an hour.

http://storage.kernelci.org/next/next-20160118/arm-multi_v7_defconfig+CONFIG_THUMB2_KERNEL=y/lab-tbaker/boot-tegra124-jetson-tk1.html

http://pastebin.com/gHSJpZbA

**Comment by EmbeddedAndroid** [comment]
Fixed in -next

http://kernelci.org/boot/all/job/next/kernel/next-20160202/ by "[PATCH] PM / devfreq: tegra: Set freq in rate callback"
